require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PotluckItemsController do

  # This should return the minimal set of attributes required to create a valid
  # PotluckItem. As you add validations to PotluckItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PotluckItemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all potluck_items as @potluck_items" do
      potluck_item = PotluckItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:potluck_items).should eq([potluck_item])
    end
  end

  describe "GET show" do
    it "assigns the requested potluck_item as @potluck_item" do
      potluck_item = PotluckItem.create! valid_attributes
      get :show, {:id => potluck_item.to_param}, valid_session
      assigns(:potluck_item).should eq(potluck_item)
    end
  end

  describe "GET new" do
    it "assigns a new potluck_item as @potluck_item" do
      get :new, {}, valid_session
      assigns(:potluck_item).should be_a_new(PotluckItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested potluck_item as @potluck_item" do
      potluck_item = PotluckItem.create! valid_attributes
      get :edit, {:id => potluck_item.to_param}, valid_session
      assigns(:potluck_item).should eq(potluck_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PotluckItem" do
        expect {
          post :create, {:potluck_item => valid_attributes}, valid_session
        }.to change(PotluckItem, :count).by(1)
      end

      it "assigns a newly created potluck_item as @potluck_item" do
        post :create, {:potluck_item => valid_attributes}, valid_session
        assigns(:potluck_item).should be_a(PotluckItem)
        assigns(:potluck_item).should be_persisted
      end

      it "redirects to the created potluck_item" do
        post :create, {:potluck_item => valid_attributes}, valid_session
        response.should redirect_to(PotluckItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved potluck_item as @potluck_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        PotluckItem.any_instance.stub(:save).and_return(false)
        post :create, {:potluck_item => {  }}, valid_session
        assigns(:potluck_item).should be_a_new(PotluckItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PotluckItem.any_instance.stub(:save).and_return(false)
        post :create, {:potluck_item => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested potluck_item" do
        potluck_item = PotluckItem.create! valid_attributes
        # Assuming there are no other potluck_items in the database, this
        # specifies that the PotluckItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PotluckItem.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => potluck_item.to_param, :potluck_item => { "these" => "params" }}, valid_session
      end

      it "assigns the requested potluck_item as @potluck_item" do
        potluck_item = PotluckItem.create! valid_attributes
        put :update, {:id => potluck_item.to_param, :potluck_item => valid_attributes}, valid_session
        assigns(:potluck_item).should eq(potluck_item)
      end

      it "redirects to the potluck_item" do
        potluck_item = PotluckItem.create! valid_attributes
        put :update, {:id => potluck_item.to_param, :potluck_item => valid_attributes}, valid_session
        response.should redirect_to(potluck_item)
      end
    end

    describe "with invalid params" do
      it "assigns the potluck_item as @potluck_item" do
        potluck_item = PotluckItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PotluckItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => potluck_item.to_param, :potluck_item => {  }}, valid_session
        assigns(:potluck_item).should eq(potluck_item)
      end

      it "re-renders the 'edit' template" do
        potluck_item = PotluckItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PotluckItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => potluck_item.to_param, :potluck_item => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested potluck_item" do
      potluck_item = PotluckItem.create! valid_attributes
      expect {
        delete :destroy, {:id => potluck_item.to_param}, valid_session
      }.to change(PotluckItem, :count).by(-1)
    end

    it "redirects to the potluck_items list" do
      potluck_item = PotluckItem.create! valid_attributes
      delete :destroy, {:id => potluck_item.to_param}, valid_session
      response.should redirect_to(potluck_items_url)
    end
  end

end
